version: 2

jobs:
  "cargo_build_debug":
    docker:
      - image: cimg/rust:1.62.0
    steps:
      - checkout
      - run: cargo build
  "cargo_build_release":
    docker:
      - image: cimg/rust:1.62.0
    steps:
      - checkout
      - run: cargo build --release
  "cmake_build_debug":
    docker:
      - image: cimg/rust:1.62.0
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - run: |
          mkdir build
          pushd build
          cmake -DCMAKE_BUILD_TYPE=Debug ..
          cmake --build . --config Debug
          popd
  "cmake_build_release":
    docker:
      - image: cimg/rust:1.62.0
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y cmake
      - run: |
          mkdir build
          pushd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release
          popd

workflows:
  version: 2
  build:
    jobs:
      - "cargo_build_debug"
      - "cargo_build_release"
      - "cmake_build_debug"
      - "cmake_build_release"
